language: node_js
# node version is read from .nvmrc

install:
    - npm install -g serverless

before_script:
  - yarn test

deploy:
  provider: script
  role:
    - $AWS_ROLE
  script: yarn install --prod && AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_REGION=$AWS_DEFAULT_REGION sls deploy function -f orestarScraper --stage production --verbose
  on:
    branch: develop