language: node_js
# node version is read from .nvmrc
before_script:
  - yarn test
deploy:
  provider: script
  script:  AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY AWS_REGION=$AWS_DEFAULT_REGION sls deploy
  on:
    branch: develop