language: node_js
# node version is read from .nvmrc
before_script:
  - yarn test
deploy:
  provider: script
  script: sls deploy
  region: $AWS_DEFAULT_REGION
  access_key_id: $AWS_SECRET_ACCESS_KEY
  secret_access_key: $AWS_ACCESS_KEY_ID
  on:
    branch: develop